// export const jd = {
//   "jobId":"789Jb12",
//   "companyName":"Company Name",
//   "jobTitle": "Software Engineer",
//   "department": "Technology",
//   "domain": "IT",
//   "companyLogo":"https://png.pngtree.com/element_pic/16/11/03/dda587d35b48fd01947cf38931323161.jpg",
//   "location": "Remote",
//   "jobType": "Full-time",
//   "salaryRange": "60,000 - 80,000 ₹ per year",
//   "jobLevel": "Mid",
//   "employmentType": "Permanent",
//   "jobDescriptionSummary": "As a Software Development Engineer – Connectivity you will engage with an experienced cross-disciplinary staff to conceive and design innovative consumer products. Vertically your ownership can span across application, device framework, connectivity stack, drivers and low level wireless controller coexistence and scheduler algorithms. Horizontally you will be given to opportunity to work and own connectivity solutions across all Ring devices spanning from Doorbells, Cameras devices to IoT Smart Home security solutions. You will work on Wi-Fi, Bluetooth BR/EDR/BLE protocols and network stacks like TCP/IP, Thread, BLE Mesh and Matter and across use cases.You will work closely with the product management, hardware, operations, application, platform, cloud and quality assurance teams. You must be responsive, flexible, and able to succeed within an open and collaborative peer environment. The Ring Connectivity team is responsible for the connectivity related user experience and use cases across Ring portfolio.",
//   "requiredSkills": [
//     "JavaScript",
//     "React.js",
//     "Node.js",
//     "MongoDB",
//     "Git"
//   ],
//   "experienceLevel": "3 to 10",
//   "educationalRequirements": ["Bachelor's degree in Computer Science or equivalent"],
//   "preferredQualifications": ["Experience with cloud services (AWS, Azure)"],
//   "jobResponsibilities": [
//     "Create and productize Connectivity stack SDK that includes L2 and L3 protocols for Linux and RTOS",
//     "Drive system engineering efforts to achieve best-in-class Wi-Fi performance, power consumption and stability",
//     "Be responsible for the architecture of software solutions, determining current limitations and compatibilities between subsystems, selection of new concepts and methodology, and hands-on development of major Wi-Fi components",
//     "Prepare technical requirements and software design specifications",
//     "Investigate, prototype, and deliver new and innovative connectivity solutions"
//   ],
//   "benefits": [
//     "Health insurance",
//     "Flexible working hours",
//     "Remote work options",
//     "Annual performance bonuses"
//   ],
//   "postedOn":"Jun 10 2024",
//   "deadline": "2024-12-31"
// }
// export const requiredSkills = [
//   { id: 1, skill: "C++" },
//   { id: 2, skill: "Java" },
//   { id: 3, skill: "Python" },
//   { id: 4, skill: "JavaScript" },
//   { id: 5, skill: "HTML" },
//   { id: 6, skill: "CSS" },
//   { id: 7, skill: "SQL" },
//   { id: 8, skill: "Ruby" },
//   { id: 9, skill: "PHP" },
//   { id: 10, skill: "Swift" },
//   { id: 11, skill: "Kotlin" },
//   { id: 12, skill: "TypeScript" },
//   { id: 13, skill: "Go" },
//   { id: 14, skill: "R" },
//   { id: 15, skill: "Scala" },
//   { id: 16, skill: "Perl" },
//   { id: 17, skill: "Shell Scripting" },
//   { id: 18, skill: "Rust" },
//   { id: 19, skill: "MATLAB" },
//   { id: 20, skill: "Dart" },
//   { id: 21, skill: "Objective-C" },
//   { id: 22, skill: "Assembly" },
//   { id: 23, skill: "Visual Basic" },
//   { id: 24, skill: "C#" },
//   { id: 25, skill: "F#" },
//   { id: 26, skill: "PowerShell" },
//   { id: 27, skill: "PL/SQL" },
//   { id: 28, skill: "SAS" },
//   { id: 29, skill: "COBOL" },
//   { id: 30, skill: "VB.NET" },
//   { id: 31, skill: "Delphi" },
//   { id: 32, skill: "Fortran" },
//   { id: 33, skill: "Groovy" },
//   { id: 34, skill: "Haskell" },
//   { id: 35, skill: "Lua" },
//   { id: 36, skill: "Erlang" },
//   { id: 37, skill: "Elixir" },
//   { id: 38, skill: "Prolog" },
//   { id: 39, skill: "Ada" },
//   { id: 40, skill: "AWK" },
//   { id: 41, skill: "PostgreSQL" },
//   { id: 42, skill: "MongoDB" },
//   { id: 43, skill: "GraphQL" },
//   { id: 44, skill: "React" },
//   { id: 45, skill: "Angular" },
//   { id: 46, skill: "Vue.js" },
//   { id: 47, skill: "Node.js" },
//   { id: 48, skill: "Spring Boot" },
//   { id: 49, skill: "Django" },
//   { id: 50, skill: "Flask" },
//   { id: 51, skill: "Laravel" },
//   { id: 52, skill: "ASP.NET" },
//   { id: 53, skill: "Redux" },
//   { id: 54, skill: "jQuery" },
//   { id: 55, skill: "Bootstrap" },
//   { id: 56, skill: "TensorFlow" },
//   { id: 57, skill: "PyTorch" },
//   { id: 58, skill: "Keras" },
//   { id: 59, skill: "OpenCV" },
//   { id: 60, skill: "Pandas" },
//   { id: 61, skill: "NumPy" },
//   { id: 62, skill: "Scikit-learn" },
//   { id: 63, skill: "Tableau" },
//   { id: 64, skill: "Power BI" },
//   { id: 65, skill: "Hadoop" },
//   { id: 66, skill: "Spark" },
//   { id: 67, skill: "Kafka" },
//   { id: 68, skill: "Docker" },
//   { id: 69, skill: "Kubernetes" },
//   { id: 70, skill: "Terraform" },
//   { id: 71, skill: "Ansible" },
//   { id: 72, skill: "Jenkins" },
//   { id: 73, skill: "CI/CD" },
//   { id: 74, skill: "Linux" },
//   { id: 75, skill: "AWS" },
//   { id: 76, skill: "Azure" },
//   { id: 77, skill: "GCP (Google Cloud Platform)" },
//   { id: 78, skill: "BigQuery" },
//   { id: 79, skill: "Firebase" },
//   { id: 80, skill: "REST APIs" },
//   { id: 81, skill: "GraphQL APIs" },
//   { id: 82, skill: "SOAP APIs" },
//   { id: 83, skill: "Webpack" },
//   { id: 84, skill: "Babel" },
//   { id: 85, skill: "Git" },
//   { id: 86, skill: "SVN" },
//   { id: 87, skill: "JUnit" },
//   { id: 88, skill: "Selenium" },
//   { id: 89, skill: "Cypress" },
//   { id: 90, skill: "Jest" },
//   { id: 91, skill: "Mocha" },
//   { id: 92, skill: "Chai" },
//   { id: 93, skill: "Postman" },
//   { id: 94, skill: "Swagger" },
//   { id: 95, skill: "Figma" },
//   { id: 96, skill: "Adobe XD" },
//   { id: 97, skill: "Canva" },
//   { id: 98, skill: "Blender" },
//   { id: 99, skill: "Unity" },
//   { id: 100, skill: "Unreal Engine" },
// ];  
// export const COMPANY_LOGO="https://png.pngtree.com/element_pic/16/11/03/dda587d35b48fd01947cf38931323161.jpg";
// export const stateCityConst=[
// {
//   "id": 1,
//   "state": "Andhra Pradesh",
//   "cities": ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Kurnool"]
// },
// {
//   "id": 2,
//   "state": "Arunachal Pradesh",
//   "cities": ["Itanagar", "Naharlagun", "Pasighat", "Tawang", "Ziro"]
// },
// {
//   "id": 3,
//   "state": "Assam",
//   "cities": ["Guwahati", "Silchar", "Dibrugarh", "Tezpur", "Jorhat"]
// },
// {
//   "id": 4,
//   "state": "Bihar",
//   "cities": ["Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Purnia"]
// },
// {
//   "id": 5,
//   "state": "Chhattisgarh",
//   "cities": ["Raipur", "Bhilai", "Bilaspur", "Korba", "Durg"]
// },
// {
//   "id": 6,
//   "state": "Goa",
//   "cities": ["Panaji", "Margao", "Vasco da Gama", "Mapusa", "Ponda"]
// },
// {
//   "id": 7,
//   "state": "Gujarat",
//   "cities": ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Gandhinagar"]
// },
// {
//   "id": 8,
//   "state": "Haryana",
//   "cities": ["Chandigarh", "Gurugram", "Faridabad", "Panipat", "Ambala"]
// },
// {
//   "id": 9,
//   "state": "Himachal Pradesh",
//   "cities": ["Shimla", "Dharamshala", "Manali", "Mandi", "Solan"]
// },
// {
//   "id": 10,
//   "state": "Jharkhand",
//   "cities": ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Hazaribagh"]
// },
// {
//   "id": 11,
//   "state": "Karnataka",
//   "cities": ["Bengaluru", "Mysuru", "Mangaluru", "Hubballi", "Belagavi"]
// },
// {
//   "id": 12,
//   "state": "Kerala",
//   "cities": ["Thiruvananthapuram", "Kochi", "Kozhikode", "Kannur", "Thrissur"]
// },
// {
//   "id": 13,
//   "state": "Madhya Pradesh",
//   "cities": ["Bhopal", "Indore", "Gwalior", "Jabalpur", "Ujjain"]
// },
// {
//   "id": 14,
//   "state": "Maharashtra",
//   "cities": ["Mumbai", "Pune", "Nagpur", "Thane", "Nashik"]
// },
// {
//   "id": 15,
//   "state": "Manipur",
//   "cities": ["Imphal", "Churachandpur", "Bishnupur", "Thoubal", "Ukhrul"]
// },
// {
//   "id": 16,
//   "state": "Meghalaya",
//   "cities": ["Shillong", "Tura", "Nongstoin", "Jowai", "Baghmara"]
// },
// {
//   "id": 17,
//   "state": "Mizoram",
//   "cities": ["Aizawl", "Lunglei", "Champhai", "Serchhip", "Kolasib"]
// },
// {
//   "id": 18,
//   "state": "Nagaland",
//   "cities": ["Kohima", "Dimapur", "Mokokchung", "Tuensang", "Wokha"]
// },
// {
//   "id": 19,
//   "state": "Odisha",
//   "cities": ["Bhubaneswar", "Cuttack", "Rourkela", "Sambalpur", "Berhampur"]
// },
// {
//   "id": 20,
//   "state": "Punjab",
//   "cities": ["Chandigarh", "Ludhiana", "Amritsar", "Jalandhar", "Patiala"]
// },
// {
//   "id": 21,
//   "state": "Rajasthan",
//   "cities": ["Jaipur", "Udaipur", "Jodhpur", "Kota", "Ajmer"]
// },
// {
//   "id": 22,
//   "state": "Sikkim",
//   "cities": ["Gangtok", "Namchi", "Gyalshing", "Ravangla", "Mangan"]
// },
// {
//   "id": 23,
//   "state": "Tamil Nadu",
//   "cities": ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem"]
// },
// {
//   "id": 24,
//   "state": "Telangana",
//   "cities": ["Hyderabad", "Warangal", "Nizamabad", "Karimnagar", "Khammam"]
// },
// {
//   "id": 25,
//   "state": "Tripura",
//   "cities": ["Agartala", "Dharmanagar", "Udaipur", "Kailashahar", "Belonia"]
// },
// {
//   "id": 26,
//   "state": "Uttar Pradesh",
//   "cities": ["Lucknow", "Kanpur", "Varanasi", "Agra", "Meerut"]
// },
// {
//   "id": 27,
//   "state": "Uttarakhand",
//   "cities": ["Dehradun", "Haridwar", "Rishikesh", "Nainital", "Haldwani"]
// },
// {
//   "id": 28,
//   "state": "West Bengal",
//   "cities": ["Kolkata", "Howrah", "Durgapur", "Siliguri", "Asansol"]
// }
// ];
// export const softSkills = [
// { "id": 1, "skill": "Communication" },
// { "id": 2, "skill": "Teamwork" },
// { "id": 3, "skill": "Problem-solving" },
// { "id": 4, "skill": "Leadership" },
// { "id": 5, "skill": "Time Management" },
// { "id": 6, "skill": "Adaptability" },
// { "id": 7, "skill": "Creativity" },
// { "id": 8, "skill": "Critical Thinking" },
// { "id": 9, "skill": "Conflict Resolution" },
// { "id": 10, "skill": "Emotional Intelligence" },
// { "id": 11, "skill": "Negotiation" },
// { "id": 12, "skill": "Decision Making" },
// { "id": 13, "skill": "Active Listening" },
// { "id": 14, "skill": "Collaboration" },
// { "id": 15, "skill": "Networking" }
// ]

// export const preferredSkills = [
// { "id": 1, "skill": "Communication" },
// { "id": 2, "skill": "Teamwork" },
// { "id": 3, "skill": "Problem-solving" },
// { "id": 4, "skill": "Leadership" },
// { "id": 5, "skill": "Time Management" },
// { "id": 6, "skill": "Adaptability" },
// { "id": 7, "skill": "Creativity" },
// { "id": 8, "skill": "Critical Thinking" },
// { "id": 9, "skill": "Conflict Resolution" },
// { "id": 10, "skill": "Emotional Intelligence" },
// { "id": 11, "skill": "Negotiation" },
// { "id": 12, "skill": "Decision Making" },
// { "id": 13, "skill": "Active Listening" },
// { "id": 14, "skill": "Collaboration" },
// { "id": 15, "skill": "Networking" },
// { id: 1, skill: "C++" },
//   { id: 2, skill: "Java" },
//   { id: 3, skill: "Python" },
//   { id: 4, skill: "JavaScript" },
//   { id: 5, skill: "HTML" },
//   { id: 6, skill: "CSS" },
//   { id: 7, skill: "SQL" },
//   { id: 8, skill: "Ruby" },
//   { id: 9, skill: "PHP" },
//   { id: 10, skill: "Swift" },
//   { id: 11, skill: "Kotlin" },
//   { id: 12, skill: "TypeScript" },
//   { id: 13, skill: "Go" },
//   { id: 14, skill: "R" },
//   { id: 15, skill: "Scala" },
//   { id: 16, skill: "Perl" },
//   { id: 17, skill: "Shell Scripting" },
//   { id: 18, skill: "Rust" },
//   { id: 19, skill: "MATLAB" },
//   { id: 20, skill: "Dart" },
//   { id: 21, skill: "Objective-C" },
//   { id: 22, skill: "Assembly" },
//   { id: 23, skill: "Visual Basic" },
//   { id: 24, skill: "C#" },
//   { id: 25, skill: "F#" },
//   { id: 26, skill: "PowerShell" },
//   { id: 27, skill: "PL/SQL" },
//   { id: 28, skill: "SAS" },
//   { id: 29, skill: "COBOL" },
//   { id: 30, skill: "VB.NET" },
//   { id: 31, skill: "Delphi" },
//   { id: 32, skill: "Fortran" },
//   { id: 33, skill: "Groovy" },
//   { id: 34, skill: "Haskell" },
//   { id: 35, skill: "Lua" },
//   { id: 36, skill: "Erlang" },
//   { id: 37, skill: "Elixir" },
//   { id: 38, skill: "Prolog" },
//   { id: 39, skill: "Ada" },
//   { id: 40, skill: "AWK" },
//   { id: 41, skill: "PostgreSQL" },
//   { id: 42, skill: "MongoDB" },
//   { id: 43, skill: "GraphQL" },
//   { id: 44, skill: "React" },
//   { id: 45, skill: "Angular" },
//   { id: 46, skill: "Vue.js" },
//   { id: 47, skill: "Node.js" },
//   { id: 48, skill: "Spring Boot" },
//   { id: 49, skill: "Django" },
//   { id: 50, skill: "Flask" },
//   { id: 51, skill: "Laravel" },
//   { id: 52, skill: "ASP.NET" },
//   { id: 53, skill: "Redux" },
//   { id: 54, skill: "jQuery" },
//   { id: 55, skill: "Bootstrap" },
//   { id: 56, skill: "TensorFlow" },
//   { id: 57, skill: "PyTorch" },
//   { id: 58, skill: "Keras" },
//   { id: 59, skill: "OpenCV" },
//   { id: 60, skill: "Pandas" },
//   { id: 61, skill: "NumPy" },
//   { id: 62, skill: "Scikit-learn" },
//   { id: 63, skill: "Tableau" },
//   { id: 64, skill: "Power BI" },
//   { id: 65, skill: "Hadoop" },
//   { id: 66, skill: "Spark" },
//   { id: 67, skill: "Kafka" },
//   { id: 68, skill: "Docker" },
//   { id: 69, skill: "Kubernetes" },
//   { id: 70, skill: "Terraform" },
//   { id: 71, skill: "Ansible" },
//   { id: 72, skill: "Jenkins" },
//   { id: 73, skill: "CI/CD" },
//   { id: 74, skill: "Linux" },
//   { id: 75, skill: "AWS" },
//   { id: 76, skill: "Azure" },
//   { id: 77, skill: "GCP (Google Cloud Platform)" },
//   { id: 78, skill: "BigQuery" },
//   { id: 79, skill: "Firebase" },
//   { id: 80, skill: "REST APIs" },
//   { id: 81, skill: "GraphQL APIs" },
//   { id: 82, skill: "SOAP APIs" },
//   { id: 83, skill: "Webpack" },
//   { id: 84, skill: "Babel" },
//   { id: 85, skill: "Git" },
//   { id: 86, skill: "SVN" },
//   { id: 87, skill: "JUnit" },
//   { id: 88, skill: "Selenium" },
//   { id: 89, skill: "Cypress" },
//   { id: 90, skill: "Jest" },
//   { id: 91, skill: "Mocha" },
//   { id: 92, skill: "Chai" },
//   { id: 93, skill: "Postman" },
//   { id: 94, skill: "Swagger" },
//   { id: 95, skill: "Figma" },
//   { id: 96, skill: "Adobe XD" },
//   { id: 97, skill: "Canva" },
//   { id: 98, skill: "Blender" },
//   { id: 99, skill: "Unity" },
//   { id: 100, skill: "Unreal Engine" },
// ]

// export const experiencedSkills = [
// { "id": 1, "skill": "Communication" },
// { "id": 2, "skill": "Teamwork" },
// { "id": 3, "skill": "Problem-solving" },
// { "id": 4, "skill": "Leadership" },
// { "id": 5, "skill": "Time Management" },
// { "id": 6, "skill": "Adaptability" },
// { "id": 7, "skill": "Creativity" },
// { "id": 8, "skill": "Critical Thinking" },
// { "id": 9, "skill": "Conflict Resolution" },
// { "id": 10, "skill": "Emotional Intelligence" },
// { "id": 11, "skill": "Negotiation" },
// { "id": 12, "skill": "Decision Making" },
// { "id": 13, "skill": "Active Listening" },
// { "id": 14, "skill": "Collaboration" },
// { "id": 15, "skill": "Networking" },
// { id: 1, skill: "C++" },
//   { id: 2, skill: "Java" },
//   { id: 3, skill: "Python" },
//   { id: 4, skill: "JavaScript" },
//   { id: 5, skill: "HTML" },
//   { id: 6, skill: "CSS" },
//   { id: 7, skill: "SQL" },
//   { id: 8, skill: "Ruby" },
//   { id: 9, skill: "PHP" },
//   { id: 10, skill: "Swift" },
//   { id: 11, skill: "Kotlin" },
//   { id: 12, skill: "TypeScript" },
//   { id: 13, skill: "Go" },
//   { id: 14, skill: "R" },
//   { id: 15, skill: "Scala" },
//   { id: 16, skill: "Perl" },
//   { id: 17, skill: "Shell Scripting" },
//   { id: 18, skill: "Rust" },
//   { id: 19, skill: "MATLAB" },
//   { id: 20, skill: "Dart" },
//   { id: 21, skill: "Objective-C" },
//   { id: 22, skill: "Assembly" },
//   { id: 23, skill: "Visual Basic" },
//   { id: 24, skill: "C#" },
//   { id: 25, skill: "F#" },
//   { id: 26, skill: "PowerShell" },
//   { id: 27, skill: "PL/SQL" },
//   { id: 28, skill: "SAS" },
//   { id: 29, skill: "COBOL" },
//   { id: 30, skill: "VB.NET" },
//   { id: 31, skill: "Delphi" },
//   { id: 32, skill: "Fortran" },
//   { id: 33, skill: "Groovy" },
//   { id: 34, skill: "Haskell" },
//   { id: 35, skill: "Lua" },
//   { id: 36, skill: "Erlang" },
//   { id: 37, skill: "Elixir" },
//   { id: 38, skill: "Prolog" },
//   { id: 39, skill: "Ada" },
//   { id: 40, skill: "AWK" },
//   { id: 41, skill: "PostgreSQL" },
//   { id: 42, skill: "MongoDB" },
//   { id: 43, skill: "GraphQL" },
//   { id: 44, skill: "React" },
//   { id: 45, skill: "Angular" },
//   { id: 46, skill: "Vue.js" },
//   { id: 47, skill: "Node.js" },
//   { id: 48, skill: "Spring Boot" },
//   { id: 49, skill: "Django" },
//   { id: 50, skill: "Flask" },
//   { id: 51, skill: "Laravel" },
//   { id: 52, skill: "ASP.NET" },
//   { id: 53, skill: "Redux" },
//   { id: 54, skill: "jQuery" },
//   { id: 55, skill: "Bootstrap" },
//   { id: 56, skill: "TensorFlow" },
//   { id: 57, skill: "PyTorch" },
//   { id: 58, skill: "Keras" },
//   { id: 59, skill: "OpenCV" },
//   { id: 60, skill: "Pandas" },
//   { id: 61, skill: "NumPy" },
//   { id: 62, skill: "Scikit-learn" },
//   { id: 63, skill: "Tableau" },
//   { id: 64, skill: "Power BI" },
//   { id: 65, skill: "Hadoop" },
//   { id: 66, skill: "Spark" },
//   { id: 67, skill: "Kafka" },
//   { id: 68, skill: "Docker" },
//   { id: 69, skill: "Kubernetes" },
//   { id: 70, skill: "Terraform" },
//   { id: 71, skill: "Ansible" },
//   { id: 72, skill: "Jenkins" },
//   { id: 73, skill: "CI/CD" },
//   { id: 74, skill: "Linux" },
//   { id: 75, skill: "AWS" },
//   { id: 76, skill: "Azure" },
//   { id: 77, skill: "GCP (Google Cloud Platform)" },
//   { id: 78, skill: "BigQuery" },
//   { id: 79, skill: "Firebase" },
//   { id: 80, skill: "REST APIs" },
//   { id: 81, skill: "GraphQL APIs" },
//   { id: 82, skill: "SOAP APIs" },
//   { id: 83, skill: "Webpack" },
//   { id: 84, skill: "Babel" },
//   { id: 85, skill: "Git" },
//   { id: 86, skill: "SVN" },
//   { id: 87, skill: "JUnit" },
//   { id: 88, skill: "Selenium" },
//   { id: 89, skill: "Cypress" },
//   { id: 90, skill: "Jest" },
//   { id: 91, skill: "Mocha" },
//   { id: 92, skill: "Chai" },
//   { id: 93, skill: "Postman" },
//   { id: 94, skill: "Swagger" },
//   { id: 95, skill: "Figma" },
//   { id: 96, skill: "Adobe XD" },
//   { id: 97, skill: "Canva" },
//   { id: 98, skill: "Blender" },
//   { id: 99, skill: "Unity" },
//   { id: 100, skill: "Unreal Engine" },
// ]
// export const jobTitle=[
// {id:1,title:"ASDE"},
// {id:2,title:"SDE 1"},
// {id:3,title:"SDE 2"},
// {id:4,title:"Software Engineer"},
// {id:5,title:"Tester"},
// {id:6,title:"Technical Trainer"},
// {id:5,title:"Assistant Professor"}
// ]

export const jd = {
  "jobId":"789Jb12",
  "companyName":"Company Name",
  "jobTitle": "Software Engineer",
  "department": "Technology",
  "domain": "IT",
  "companyLogo":"https://png.pngtree.com/element_pic/16/11/03/dda587d35b48fd01947cf38931323161.jpg",
  "location": "Remote",
  "jobType": "Full-time",
  "salaryRange": "60,000 - 80,000 ₹ per year",
  "jobLevel": "Mid",
  "employmentType": "Permanent",
  "jobDescriptionSummary": "As a Software Development Engineer – Connectivity you will engage with an experienced cross-disciplinary staff to conceive and design innovative consumer products. Vertically your ownership can span across application, device framework, connectivity stack, drivers and low level wireless controller coexistence and scheduler algorithms. Horizontally you will be given to opportunity to work and own connectivity solutions across all Ring devices spanning from Doorbells, Cameras devices to IoT Smart Home security solutions. You will work on Wi-Fi, Bluetooth BR/EDR/BLE protocols and network stacks like TCP/IP, Thread, BLE Mesh and Matter and across use cases.You will work closely with the product management, hardware, operations, application, platform, cloud and quality assurance teams. You must be responsive, flexible, and able to succeed within an open and collaborative peer environment. The Ring Connectivity team is responsible for the connectivity related user experience and use cases across Ring portfolio.",
  "requiredSkills": [
    "JavaScript",
    "React.js",
    "Node.js",
    "MongoDB",
    "Git"
  ],
  "experienceLevel": "3 to 10",
  "educationalRequirements": ["Bachelor's degree in Computer Science or equivalent"],
  "preferredQualifications": ["Experience with cloud services (AWS, Azure)"],
  "jobResponsibilities": [
    "Create and productize Connectivity stack SDK that includes L2 and L3 protocols for Linux and RTOS",
    "Drive system engineering efforts to achieve best-in-class Wi-Fi performance, power consumption and stability",
    "Be responsible for the architecture of software solutions, determining current limitations and compatibilities between subsystems, selection of new concepts and methodology, and hands-on development of major Wi-Fi components",
    "Prepare technical requirements and software design specifications",
    "Investigate, prototype, and deliver new and innovative connectivity solutions"
  ],
  "benefits": [
    "Health insurance",
    "Flexible working hours",
    "Remote work options",
    "Annual performance bonuses"
  ],
  "postedOn":"Jun 10 2024",
  "deadline": "2024-12-31"
}
export const requiredSkills = [
  { id: 1, skill: "C++" },
  { id: 2, skill: "Java" },
  { id: 3, skill: "Python" },
  { id: 4, skill: "JavaScript" },
  { id: 5, skill: "HTML" },
  { id: 6, skill: "CSS" },
  { id: 7, skill: "SQL" },
  { id: 8, skill: "Ruby" },
  { id: 9, skill: "PHP" },
  { id: 10, skill: "Swift" },
  { id: 11, skill: "Kotlin" },
  { id: 12, skill: "TypeScript" },
  { id: 13, skill: "Go" },
  { id: 14, skill: "R" },
  { id: 15, skill: "Scala" },
  { id: 16, skill: "Perl" },
  { id: 17, skill: "Shell Scripting" },
  { id: 18, skill: "Rust" },
  { id: 19, skill: "MATLAB" },
  { id: 20, skill: "Dart" },
  { id: 21, skill: "Objective-C" },
  { id: 22, skill: "Assembly" },
  { id: 23, skill: "Visual Basic" },
  { id: 24, skill: "C#" },
  { id: 25, skill: "F#" },
  { id: 26, skill: "PowerShell" },
  { id: 27, skill: "PL/SQL" },
  { id: 28, skill: "SAS" },
  { id: 29, skill: "COBOL" },
  { id: 30, skill: "VB.NET" },
  { id: 31, skill: "Delphi" },
  { id: 32, skill: "Fortran" },
  { id: 33, skill: "Groovy" },
  { id: 34, skill: "Haskell" },
  { id: 35, skill: "Lua" },
  { id: 36, skill: "Erlang" },
  { id: 37, skill: "Elixir" },
  { id: 38, skill: "Prolog" },
  { id: 39, skill: "Ada" },
  { id: 40, skill: "AWK" },
  { id: 41, skill: "PostgreSQL" },
  { id: 42, skill: "MongoDB" },
  { id: 43, skill: "GraphQL" },
  { id: 44, skill: "React" },
  { id: 45, skill: "Angular" },
  { id: 46, skill: "Vue.js" },
  { id: 47, skill: "Node.js" },
  { id: 48, skill: "Spring Boot" },
  { id: 49, skill: "Django" },
  { id: 50, skill: "Flask" },
  { id: 51, skill: "Laravel" },
  { id: 52, skill: "ASP.NET" },
  { id: 53, skill: "Redux" },
  { id: 54, skill: "jQuery" },
  { id: 55, skill: "Bootstrap" },
  { id: 56, skill: "TensorFlow" },
  { id: 57, skill: "PyTorch" },
  { id: 58, skill: "Keras" },
  { id: 59, skill: "OpenCV" },
  { id: 60, skill: "Pandas" },
  { id: 61, skill: "NumPy" },
  { id: 62, skill: "Scikit-learn" },
  { id: 63, skill: "Tableau" },
  { id: 64, skill: "Power BI" },
  { id: 65, skill: "Hadoop" },
  { id: 66, skill: "Spark" },
  { id: 67, skill: "Kafka" },
  { id: 68, skill: "Docker" },
  { id: 69, skill: "Kubernetes" },
  { id: 70, skill: "Terraform" },
  { id: 71, skill: "Ansible" },
  { id: 72, skill: "Jenkins" },
  { id: 73, skill: "CI/CD" },
  { id: 74, skill: "Linux" },
  { id: 75, skill: "AWS" },
  { id: 76, skill: "Azure" },
  { id: 77, skill: "GCP (Google Cloud Platform)" },
  { id: 78, skill: "BigQuery" },
  { id: 79, skill: "Firebase" },
  { id: 80, skill: "REST APIs" },
  { id: 81, skill: "GraphQL APIs" },
  { id: 82, skill: "SOAP APIs" },
  { id: 83, skill: "Webpack" },
  { id: 84, skill: "Babel" },
  { id: 85, skill: "Git" },
  { id: 86, skill: "SVN" },
  { id: 87, skill: "JUnit" },
  { id: 88, skill: "Selenium" },
  { id: 89, skill: "Cypress" },
  { id: 90, skill: "Jest" },
  { id: 91, skill: "Mocha" },
  { id: 92, skill: "Chai" },
  { id: 93, skill: "Postman" },
  { id: 94, skill: "Swagger" },
  { id: 95, skill: "Figma" },
  { id: 96, skill: "Adobe XD" },
  { id: 97, skill: "Canva" },
  { id: 98, skill: "Blender" },
  { id: 99, skill: "Unity" },
  { id: 100, skill: "Unreal Engine" },
];  
export const COMPANY_LOGO="https://png.pngtree.com/element_pic/16/11/03/dda587d35b48fd01947cf38931323161.jpg";
export const stateCityConst=[
{
  "id": 1,
  "state": "Andhra Pradesh",
  "cities": ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Kurnool"]
},
{
  "id": 2,
  "state": "Arunachal Pradesh",
  "cities": ["Itanagar", "Naharlagun", "Pasighat", "Tawang", "Ziro"]
},
{
  "id": 3,
  "state": "Assam",
  "cities": ["Guwahati", "Silchar", "Dibrugarh", "Tezpur", "Jorhat"]
},
{
  "id": 4,
  "state": "Bihar",
  "cities": ["Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Purnia"]
},
{
  "id": 5,
  "state": "Chhattisgarh",
  "cities": ["Raipur", "Bhilai", "Bilaspur", "Korba", "Durg"]
},
{
  "id": 6,
  "state": "Goa",
  "cities": ["Panaji", "Margao", "Vasco da Gama", "Mapusa", "Ponda"]
},
{
  "id": 7,
  "state": "Gujarat",
  "cities": ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Gandhinagar"]
},
{
  "id": 8,
  "state": "Haryana",
  "cities": ["Chandigarh", "Gurugram", "Faridabad", "Panipat", "Ambala"]
},
{
  "id": 9,
  "state": "Himachal Pradesh",
  "cities": ["Shimla", "Dharamshala", "Manali", "Mandi", "Solan"]
},
{
  "id": 10,
  "state": "Jharkhand",
  "cities": ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Hazaribagh"]
},
{
  "id": 11,
  "state": "Karnataka",
  "cities": ["Bengaluru", "Mysuru", "Mangaluru", "Hubballi", "Belagavi"]
},
{
  "id": 12,
  "state": "Kerala",
  "cities": ["Thiruvananthapuram", "Kochi", "Kozhikode", "Kannur", "Thrissur"]
},
{
  "id": 13,
  "state": "Madhya Pradesh",
  "cities": ["Bhopal", "Indore", "Gwalior", "Jabalpur", "Ujjain"]
},
{
  "id": 14,
  "state": "Maharashtra",
  "cities": ["Mumbai", "Pune", "Nagpur", "Thane", "Nashik"]
},
{
  "id": 15,
  "state": "Manipur",
  "cities": ["Imphal", "Churachandpur", "Bishnupur", "Thoubal", "Ukhrul"]
},
{
  "id": 16,
  "state": "Meghalaya",
  "cities": ["Shillong", "Tura", "Nongstoin", "Jowai", "Baghmara"]
},
{
  "id": 17,
  "state": "Mizoram",
  "cities": ["Aizawl", "Lunglei", "Champhai", "Serchhip", "Kolasib"]
},
{
  "id": 18,
  "state": "Nagaland",
  "cities": ["Kohima", "Dimapur", "Mokokchung", "Tuensang", "Wokha"]
},
{
  "id": 19,
  "state": "Odisha",
  "cities": ["Bhubaneswar", "Cuttack", "Rourkela", "Sambalpur", "Berhampur"]
},
{
  "id": 20,
  "state": "Punjab",
  "cities": ["Chandigarh", "Ludhiana", "Amritsar", "Jalandhar", "Patiala"]
},
{
  "id": 21,
  "state": "Rajasthan",
  "cities": ["Jaipur", "Udaipur", "Jodhpur", "Kota", "Ajmer"]
},
{
  "id": 22,
  "state": "Sikkim",
  "cities": ["Gangtok", "Namchi", "Gyalshing", "Ravangla", "Mangan"]
},
{
  "id": 23,
  "state": "Tamil Nadu",
  "cities": ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem"]
},
{
  "id": 24,
  "state": "Telangana",
  "cities": ["Hyderabad", "Warangal", "Nizamabad", "Karimnagar", "Khammam"]
},
{
  "id": 25,
  "state": "Tripura",
  "cities": ["Agartala", "Dharmanagar", "Udaipur", "Kailashahar", "Belonia"]
},
{
  "id": 26,
  "state": "Uttar Pradesh",
  "cities": ["Lucknow", "Kanpur", "Varanasi", "Agra", "Meerut"]
},
{
  "id": 27,
  "state": "Uttarakhand",
  "cities": ["Dehradun", "Haridwar", "Rishikesh", "Nainital", "Haldwani"]
},
{
  "id": 28,
  "state": "West Bengal",
  "cities": ["Kolkata", "Howrah", "Durgapur", "Siliguri", "Asansol"]
}
];
export const countryStateCity = [
{
  id: 1,
  country: "India",
  states: [
    {
      id: 101,
      state: "Odisha",
      cities: ["Bhubaneswar", "Cuttack", "Rourkela"],
    },
    {
      id: 102,
      state: "Maharashtra",
      cities: ["Mumbai", "Pune", "Nagpur"],
    },
  ],
},
{
  id: 2,
  country: "USA",
  states: [
    {
      id: 201,
      state: "California",
      cities: ["Los Angeles", "San Francisco", "San Diego"],
    },
    {
      id: 202,
      state: "Texas",
      cities: ["Houston", "Dallas", "Austin"],
    },
  ],
},
];

export const softSkills = [
{ "id": 1, "skill": "Communication" },
{ "id": 2, "skill": "Teamwork" },
{ "id": 3, "skill": "Problem-solving" },
{ "id": 4, "skill": "Leadership" },
{ "id": 5, "skill": "Time Management" },
{ "id": 6, "skill": "Adaptability" },
{ "id": 7, "skill": "Creativity" },
{ "id": 8, "skill": "Critical Thinking" },
{ "id": 9, "skill": "Conflict Resolution" },
{ "id": 10, "skill": "Emotional Intelligence" },
{ "id": 11, "skill": "Negotiation" },
{ "id": 12, "skill": "Decision Making" },
{ "id": 13, "skill": "Active Listening" },
{ "id": 14, "skill": "Collaboration" },
{ "id": 15, "skill": "Networking" }
]

export const preferredSkills = [
{ "id": 1, "skill": "Communication" },
{ "id": 2, "skill": "Teamwork" },
{ "id": 3, "skill": "Problem-solving" },
{ "id": 4, "skill": "Leadership" },
{ "id": 5, "skill": "Time Management" },
{ "id": 6, "skill": "Adaptability" },
{ "id": 7, "skill": "Creativity" },
{ "id": 8, "skill": "Critical Thinking" },
{ "id": 9, "skill": "Conflict Resolution" },
{ "id": 10, "skill": "Emotional Intelligence" },
{ "id": 11, "skill": "Negotiation" },
{ "id": 12, "skill": "Decision Making" },
{ "id": 13, "skill": "Active Listening" },
{ "id": 14, "skill": "Collaboration" },
{ "id": 15, "skill": "Networking" },
{ id: 1, skill: "C++" },
  { id: 2, skill: "Java" },
  { id: 3, skill: "Python" },
  { id: 4, skill: "JavaScript" },
  { id: 5, skill: "HTML" },
  { id: 6, skill: "CSS" },
  { id: 7, skill: "SQL" },
  { id: 8, skill: "Ruby" },
  { id: 9, skill: "PHP" },
  { id: 10, skill: "Swift" },
  { id: 11, skill: "Kotlin" },
  { id: 12, skill: "TypeScript" },
  { id: 13, skill: "Go" },
  { id: 14, skill: "R" },
  { id: 15, skill: "Scala" },
  { id: 16, skill: "Perl" },
  { id: 17, skill: "Shell Scripting" },
  { id: 18, skill: "Rust" },
  { id: 19, skill: "MATLAB" },
  { id: 20, skill: "Dart" },
  { id: 21, skill: "Objective-C" },
  { id: 22, skill: "Assembly" },
  { id: 23, skill: "Visual Basic" },
  { id: 24, skill: "C#" },
  { id: 25, skill: "F#" },
  { id: 26, skill: "PowerShell" },
  { id: 27, skill: "PL/SQL" },
  { id: 28, skill: "SAS" },
  { id: 29, skill: "COBOL" },
  { id: 30, skill: "VB.NET" },
  { id: 31, skill: "Delphi" },
  { id: 32, skill: "Fortran" },
  { id: 33, skill: "Groovy" },
  { id: 34, skill: "Haskell" },
  { id: 35, skill: "Lua" },
  { id: 36, skill: "Erlang" },
  { id: 37, skill: "Elixir" },
  { id: 38, skill: "Prolog" },
  { id: 39, skill: "Ada" },
  { id: 40, skill: "AWK" },
  { id: 41, skill: "PostgreSQL" },
  { id: 42, skill: "MongoDB" },
  { id: 43, skill: "GraphQL" },
  { id: 44, skill: "React" },
  { id: 45, skill: "Angular" },
  { id: 46, skill: "Vue.js" },
  { id: 47, skill: "Node.js" },
  { id: 48, skill: "Spring Boot" },
  { id: 49, skill: "Django" },
  { id: 50, skill: "Flask" },
  { id: 51, skill: "Laravel" },
  { id: 52, skill: "ASP.NET" },
  { id: 53, skill: "Redux" },
  { id: 54, skill: "jQuery" },
  { id: 55, skill: "Bootstrap" },
  { id: 56, skill: "TensorFlow" },
  { id: 57, skill: "PyTorch" },
  { id: 58, skill: "Keras" },
  { id: 59, skill: "OpenCV" },
  { id: 60, skill: "Pandas" },
  { id: 61, skill: "NumPy" },
  { id: 62, skill: "Scikit-learn" },
  { id: 63, skill: "Tableau" },
  { id: 64, skill: "Power BI" },
  { id: 65, skill: "Hadoop" },
  { id: 66, skill: "Spark" },
  { id: 67, skill: "Kafka" },
  { id: 68, skill: "Docker" },
  { id: 69, skill: "Kubernetes" },
  { id: 70, skill: "Terraform" },
  { id: 71, skill: "Ansible" },
  { id: 72, skill: "Jenkins" },
  { id: 73, skill: "CI/CD" },
  { id: 74, skill: "Linux" },
  { id: 75, skill: "AWS" },
  { id: 76, skill: "Azure" },
  { id: 77, skill: "GCP (Google Cloud Platform)" },
  { id: 78, skill: "BigQuery" },
  { id: 79, skill: "Firebase" },
  { id: 80, skill: "REST APIs" },
  { id: 81, skill: "GraphQL APIs" },
  { id: 82, skill: "SOAP APIs" },
  { id: 83, skill: "Webpack" },
  { id: 84, skill: "Babel" },
  { id: 85, skill: "Git" },
  { id: 86, skill: "SVN" },
  { id: 87, skill: "JUnit" },
  { id: 88, skill: "Selenium" },
  { id: 89, skill: "Cypress" },
  { id: 90, skill: "Jest" },
  { id: 91, skill: "Mocha" },
  { id: 92, skill: "Chai" },
  { id: 93, skill: "Postman" },
  { id: 94, skill: "Swagger" },
  { id: 95, skill: "Figma" },
  { id: 96, skill: "Adobe XD" },
  { id: 97, skill: "Canva" },
  { id: 98, skill: "Blender" },
  { id: 99, skill: "Unity" },
  { id: 100, skill: "Unreal Engine" },
]

export const experiencedSkills = [
{ "id": 1, "skill": "Communication" },
{ "id": 2, "skill": "Teamwork" },
{ "id": 3, "skill": "Problem-solving" },
{ "id": 4, "skill": "Leadership" },
{ "id": 5, "skill": "Time Management" },
{ "id": 6, "skill": "Adaptability" },
{ "id": 7, "skill": "Creativity" },
{ "id": 8, "skill": "Critical Thinking" },
{ "id": 9, "skill": "Conflict Resolution" },
{ "id": 10, "skill": "Emotional Intelligence" },
{ "id": 11, "skill": "Negotiation" },
{ "id": 12, "skill": "Decision Making" },
{ "id": 13, "skill": "Active Listening" },
{ "id": 14, "skill": "Collaboration" },
{ "id": 15, "skill": "Networking" },
{ id: 1, skill: "C++" },
  { id: 2, skill: "Java" },
  { id: 3, skill: "Python" },
  { id: 4, skill: "JavaScript" },
  { id: 5, skill: "HTML" },
  { id: 6, skill: "CSS" },
  { id: 7, skill: "SQL" },
  { id: 8, skill: "Ruby" },
  { id: 9, skill: "PHP" },
  { id: 10, skill: "Swift" },
  { id: 11, skill: "Kotlin" },
  { id: 12, skill: "TypeScript" },
  { id: 13, skill: "Go" },
  { id: 14, skill: "R" },
  { id: 15, skill: "Scala" },
  { id: 16, skill: "Perl" },
  { id: 17, skill: "Shell Scripting" },
  { id: 18, skill: "Rust" },
  { id: 19, skill: "MATLAB" },
  { id: 20, skill: "Dart" },
  { id: 21, skill: "Objective-C" },
  { id: 22, skill: "Assembly" },
  { id: 23, skill: "Visual Basic" },
  { id: 24, skill: "C#" },
  { id: 25, skill: "F#" },
  { id: 26, skill: "PowerShell" },
  { id: 27, skill: "PL/SQL" },
  { id: 28, skill: "SAS" },
  { id: 29, skill: "COBOL" },
  { id: 30, skill: "VB.NET" },
  { id: 31, skill: "Delphi" },
  { id: 32, skill: "Fortran" },
  { id: 33, skill: "Groovy" },
  { id: 34, skill: "Haskell" },
  { id: 35, skill: "Lua" },
  { id: 36, skill: "Erlang" },
  { id: 37, skill: "Elixir" },
  { id: 38, skill: "Prolog" },
  { id: 39, skill: "Ada" },
  { id: 40, skill: "AWK" },
  { id: 41, skill: "PostgreSQL" },
  { id: 42, skill: "MongoDB" },
  { id: 43, skill: "GraphQL" },
  { id: 44, skill: "React" },
  { id: 45, skill: "Angular" },
  { id: 46, skill: "Vue.js" },
  { id: 47, skill: "Node.js" },
  { id: 48, skill: "Spring Boot" },
  { id: 49, skill: "Django" },
  { id: 50, skill: "Flask" },
  { id: 51, skill: "Laravel" },
  { id: 52, skill: "ASP.NET" },
  { id: 53, skill: "Redux" },
  { id: 54, skill: "jQuery" },
  { id: 55, skill: "Bootstrap" },
  { id: 56, skill: "TensorFlow" },
  { id: 57, skill: "PyTorch" },
  { id: 58, skill: "Keras" },
  { id: 59, skill: "OpenCV" },
  { id: 60, skill: "Pandas" },
  { id: 61, skill: "NumPy" },
  { id: 62, skill: "Scikit-learn" },
  { id: 63, skill: "Tableau" },
  { id: 64, skill: "Power BI" },
  { id: 65, skill: "Hadoop" },
  { id: 66, skill: "Spark" },
  { id: 67, skill: "Kafka" },
  { id: 68, skill: "Docker" },
  { id: 69, skill: "Kubernetes" },
  { id: 70, skill: "Terraform" },
  { id: 71, skill: "Ansible" },
  { id: 72, skill: "Jenkins" },
  { id: 73, skill: "CI/CD" },
  { id: 74, skill: "Linux" },
  { id: 75, skill: "AWS" },
  { id: 76, skill: "Azure" },
  { id: 77, skill: "GCP (Google Cloud Platform)" },
  { id: 78, skill: "BigQuery" },
  { id: 79, skill: "Firebase" },
  { id: 80, skill: "REST APIs" },
  { id: 81, skill: "GraphQL APIs" },
  { id: 82, skill: "SOAP APIs" },
  { id: 83, skill: "Webpack" },
  { id: 84, skill: "Babel" },
  { id: 85, skill: "Git" },
  { id: 86, skill: "SVN" },
  { id: 87, skill: "JUnit" },
  { id: 88, skill: "Selenium" },
  { id: 89, skill: "Cypress" },
  { id: 90, skill: "Jest" },
  { id: 91, skill: "Mocha" },
  { id: 92, skill: "Chai" },
  { id: 93, skill: "Postman" },
  { id: 94, skill: "Swagger" },
  { id: 95, skill: "Figma" },
  { id: 96, skill: "Adobe XD" },
  { id: 97, skill: "Canva" },
  { id: 98, skill: "Blender" },
  { id: 99, skill: "Unity" },
  { id: 100, skill: "Unreal Engine" },
]
export const jobTitle=[
{id:1,title:"Full Stack Developer"},
{id:2,title:"Backend Developer"},
{id:3,title:"Frontend Developer"},
{id:4,title:"Software Engineer"},
{id:5,title:"Data Scientist"},
{id:6,title:"DevOps Engineer"},
{id:7,title:"Assistant Professor"},
{id:8,title:"Cybersecurity Analyst"},
{id:9,title:"Accountant"},
{id:10,title:"Marketing Manager"},
{id:11,title:"Financial Analyst"},
{id:12,title:"Digital Marketing Manager"},
{id:13,title:"Social Media Manager"},
{id:14,title:"Business Development Manager"},
{id:15,title:"Technical Trainer"},
{id:16,title:"HR Manager"},
{id:17,title:"Operations Manager"},
{id:18,title:"Dept Manager"}
]

export const qualificationStreamConst = [
{
  "id": 1,
  "qualification": "High School",
  "streams": [
    "Science",
    "Commerce",
    "Arts",
    "Vocational",
    "Physical Education",
    "Home Science",
    "Fine Arts",
    "Business Studies",
    "Information Technology",
    "Environmental Studies"
  ]
},
{
  "id": 2,
  "qualification": "Intermediate",
  "streams": [
    "Science",
    "Commerce",
    "Arts",
    "Vocational",
    "Computer Applications",
    "Agriculture",
    "Physical Education",
    "Home Science",
    "Mass Communication",
    "Tourism Studies",
    "Design Technology"
  ]
},
{
  "id": 3,
  "qualification": "Diploma",
  "streams": [
    "Engineering",
    "Pharmacy",
    "Hotel Management",
    "Fashion Designing",
    "Education",
    "Agriculture",
    "Nursing",
    "Interior Design",
    "Event Management",
    "Retail Management",
    "Animation & Graphics",
    "Media & Communication",
    "Photography",
    "Sports Coaching"
  ]
},
{
  "id": 4,
  "qualification": "Undergraduate (UG)",
  "streams": [
    "BCA",
    "B.Tech",
    "B.Sc",
    "BA",
    "B.Com",
    "BBA",
    "B.Arch",
    "LLB",
    "Bachelor of Fine Arts",
    "Bachelor of Design",
    "Bachelor of Social Work",
    "Bachelor of Journalism",
    "Bachelor of Education",
    "Bachelor of Performing Arts",
    "Bachelor of Tourism Management",
    "Bachelor of Physiotherapy",
    "Bachelor of Agriculture"
  ]
},
{
  "id": 5,
  "qualification": "Postgraduate (PG)",
  "streams": [
    "MCA",
    "M.Tech",
    "M.Sc",
    "MA",
    "MBA",
    "LLM",
    "M.Com",
    "Master of Fine Arts",
    "Master of Design",
    "Master of Social Work",
    "Master of Journalism",
    "Master of Education",
    "Master of Performing Arts",
    "Master of Tourism Management",
    "Master of Public Administration",
    "Master of Physiotherapy",
    "Master of Agriculture"
  ]
},
{
  "id": 6,
  "qualification": "Doctorate",
  "streams": [
    "Ph.D. in Science",
    "Ph.D. in Engineering",
    "Ph.D. in Humanities",
    "Ph.D. in Management",
    "Ph.D. in Social Sciences",
    "Ph.D. in Law",
    "Ph.D. in Agriculture",
    "Ph.D. in Education",
    "Ph.D. in Fine Arts",
    "Ph.D. in Environmental Science",
    "Ph.D. in Linguistics",
    "Ph.D. in Public Policy"
  ]
}
]